---
- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull docker.io/ayush210/spe_mini_project:latest
      
    - name: running container
      shell: docker run -it -d ayush210/spe_mini_project
